remote_theme: poole/hyde

markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            lexicon lab
tagline:          'home'
description:      'language-based experiments on intelligence and cognition'
url:              https://thelexiconlab.github.io/
baseurl:          https://thelexiconlab.github.io/

author:
  name:           'Abhilasha Kumar'
  url:            http://abhilashak.weebly.com/

paginate:         5

