remote_theme: poole/hyde

markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            lexicon lab
tagline:          'home'
description:      '<strong><u>l</u></strong>anguage-based <strong><u>ex</u></strong>periments on <strong><u>i</u></strong>ntelligence and <strong><u>co</u>gnitio<u>n</u></strong>'
url:              https://thelexiconlab.github.io/
baseurl:          https://thelexiconlab.github.io/

author:
  name:           'Abhilasha Kumar'
  url:            http://abhilashak.weebly.com/

paginate:         5

